version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/docker'
    open-pull-requests-limit: 20
    schedule:
      interval: 'monthly'
    registries:
      - ghcr
    labels:
      - dependencies
      - docker
      - Fanout
    groups:
      dependabot-core-images:
        patterns:
          - dependabot/*
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - dependencies
      - github_actions
      - Fanout      
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 20
    schedule:
      interval: 'monthly'
    labels:
      - dependencies
      - javascript
      - Fanout
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "@typescript-eslint/parser"
          - "@vercel/ncc"
          - "eslint"
          - "eslint-*"
          - "husky"
          - "jest"
          - "jest-circus"
          - "js-yaml"
          - "json-server"
          - "lint-staged"
          - "node-forge"
          - "prettier"
          - "ts-jest"
          - "ts-node"
          - "typescript"
          - "wait-port"

registries:
  ghcr:
    type: docker-registry
    url: reg-ghcrio.artifactory-de.asml.com
    username: x
    password: ${{ secrets.DEPENDABOT_GHPR_TOKEN }}
